services:
    postgres:
        container_name: pluto_database
        restart: always
        image: 'postgres:16-alpine'
        ports:
            - '5555:5432'
        environment:
            TZ: 'America/Sao_Paulo'
            PGPASSWORD: '${DB_PASSWORD:-secret}'
            POSTGRES_DB: '${DB_DATABASE:-db}'
            POSTGRES_USER: '${DB_USERNAME:-user}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
        volumes:
            - 'pluto_database:/var/lib/postgresql/data:rw'
        networks:
            - pluto_network

volumes:
    pluto_database:
        driver: local

networks:
    pluto_network:
        driver: bridge
