export enum PasswordValidateErrorEnum {
  ERROR_LOWERCASE_REQUIRED = 'ERROR_LOWERCASE_REQUIRED',
  ERROR_UPPERCASE_REQUIRED = 'ERROR_UPPERCASE_REQUIRED',
  ERROR_NUMBER_REQUIRED = 'ERROR_NUMBER_REQUIRED',
  ERROR_SPECIAL_CHARACTER_REQUIRED = 'ERROR_SPECIAL_CHARACTER_REQUIRED',
  ERROR_MINIMUM_LENGTH_REQUIRED = 'ERROR_MINIMUM_LENGTH_REQUIRED',
}
